#!/usr/bin/env bash
# Command to make an nginx server listen on port 80, shorter version
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
./1-debugging_made_short
pkill -1 nginx
service nginx status
